.TH LIBKECCAK_STATE_WIPE 3 LIBKECCAK
.SH NAME
libkeccak_state_wipe - Securely erase sensitive data
.SH SYNOPSIS
.LP
.nf
#include <libkeccak.h>
.P
void
libkeccak_state_wipe(libkeccak_state_t *\fIstate\fP);
.fi
.P
Link with
.IR -lkeccak .
.SH DESCRIPTION
The
.BR libkeccak_state_wipe ()
function securely erases data that may be
sensitive: the state of the Keccak sponge,
and the message chunk buffer.
.SH RETURN VALUES
The
.BR libkeccak_state_wipe ()
function does not return any value.
.SH ERRORS
The
.BR libkeccak_state_wipe ()
function cannot fail.
.SH SEE ALSO
.BR libkeccak_state_wipe_message (3),
.BR libkeccak_state_wipe_sponge (3),
.BR libkeccak_state_fast_destroy (3),
.BR libkeccak_state_destroy (3),
.BR libkeccak_state_reset (3)
.SH BUGS
Please report bugs to https://github.com/maandree/libkeccak/issues or to
maandree@kth.se
