.TH LIBKECCAK_STATE_MARSHAL 3 LIBKECCAK
.SH NAME
libkeccak_state_marshal - Marshals a hash state
.SH SYNOPSIS
.nf
#include <libkeccak.h>

size_t libkeccak_state_marshal(const struct libkeccak_state *\fIstate\fP, void *\fIdata\fP);
.fi
.PP
Link with
.IR -lkeccak .
.SH DESCRIPTION
The
.BR libkeccak_state_marshal ()
function marshals
.I *state
into the beginning of
.IR data .
.PP
Specific
.I NULL
as
.I data
to get minimum usable allocation size for
.SH RETURN VALUES
The
.BR libkeccak_state_marshal ()
returns the number of bytes written to
.IR data .
.SH ERRORS
The
.BR libkeccak_state_marshal ()
function cannot fail.
.SH SEE ALSO
.BR libkeccak_state_unmarshal (3)
