.TH LIBKECCAK_HMAC_UNMARSHAL 3 LIBKECCAK
.SH NAME
libkeccak_hmac_unmarshal - Unharshals an HMAC-hashing state
.SH SYNOPSIS
.nf
#include <libkeccak.h>

size_t libkeccak_hmac_unmarshal(struct libkeccak_hmac_state *\fIstate\fP, const void *\fIdata\fP);
.fi
.PP
Link with
.IR -lkeccak .
.SH DESCRIPTION
The
.BR libkeccak_hmac_unmarshal ()
function unmarshals an HMAC-hashing state from the beginning of
.IR data .
and stores it in
.IR *state .
.SH RETURN VALUES
The
.BR libkeccak_hmac_unmarshal ()
returns the number of bytes reads from
.IR data .
.SH ERRORS
The
.BR libkeccak_hmac_unmarshal ()
function may fail for any specified for the function
.BR malloc (3).
.SH SEE ALSO
.BR libkeccak_hmac_marshal_size (3),
.BR libkeccak_hmac_marshal (3),
.BR libkeccak_hmac_unmarshal_skip (3)
