.TH LIBKECCAK_HMAC_DUPLICATE 3 LIBKECCAK
.SH NAME
libkeccak_hmac_duplicate - Allocate a duplicate an HMAC-hashing state
.SH SYNOPSIS
.nf
#include <libkeccak.h>

struct libkeccak_hmac_state *libkeccak_hmac_duplicate(const struct libkeccak_hmac_state *\fIsrc\fP);
.fi
.PP
Link with
.IR -lkeccak .
.SH DESCRIPTION
The
.BR libkeccak_hmac_duplicate ()
function allocates a new hash state and initialises
it to be identical to
.IR *src .
This includes all members of the
.B struct libkeccak_hmac_state
structure, including the state of the sponge and the
message chunk buffer.
.SH RETURN VALUES
The
.BR libkeccak_hmac_duplicate ()
function returns a newly allocated
.I libkeccak_hmac_t*
(of one initialised element) upon successful completion.
On error,
.I NULL
is returned and
.I errno
is set to describe the error.
.SH ERRORS
The
.BR libkeccak_hmac_duplicate ()
function may fail for any specified for the function
.BR malloc (3).
.SH SEE ALSO
.BR libkeccak_hmac_copy (3),
.BR libkeccak_hmac_create (3)
