.TH LIBKECCAK_HMAC_CREATE 3 LIBKECCAK
.SH NAME
libkeccak_hmac_create - Allocate and initialise HMAC-hashing state
.SH SYNOPSIS
.nf
#include <libkeccak.h>

struct libkeccak_hmac_state *libkeccak_hmac_create(const struct libkeccak_spec *\fIspec\fP, const void *\fIkey\fP, size_t \fIkey_length\fP);
.fi
.PP
Link with
.IR -lkeccak .
.SH DESCRIPTION
The
.BR libkeccak_hmac_create ()
function allocates a new
.I struct libkeccak_hmac_state *
with one initialised element, and sets the
algorithm tuning parameters to those specified by
.IR *spec ,
and the key to
.I key
of length
.IR key_length .
.SH RETURN VALUES
The
.BR libkeccak_hmac_create ()
function returns a newly allocated
.I struct libkeccak_hmac_state *
(of one initialised element) upon successful completion.
On error,
.I NULL
is returned and
.I errno
is set to describe the error.
.SH ERRORS
The
.BR libkeccak_hmac_create ()
function may fail for any specified for the functions
.BR malloc (3)
and
.BR realloc (3).
.SH SEE ALSO
.BR libkeccak_hmac_initialise (3),
.BR libkeccak_hmac_free (3),
.BR libkeccak_hmac_fast_free (3),
.BR libkeccak_hmac_duplicate (3)
