.TH LIBKECCAK_BEHEX_LOWER 3 LIBKECCAK
.SH NAME
libkeccak_behex_lower - Converts a binary hashsum to lower case hexadecimal
.SH SYNOPSIS
.LP
.nf
#include <libkeccak.h>

void libkeccak_behex_lower(char *restrict \fIoutput\fP, const void *restrict \fIhashsum\fP, size_t \fIn\fP);
.fi
.PP
Link with
.IR -lkeccak .
.SH DESCRIPTION
The
.BR libkeccak_behex_lower ()
function
converts a binary hashsum, stored in
.IR hashsum ,
to lowercase hexadecimal, and stores the
hexadecimal representation in
.IR output .
.PP
.I output
will be terminated by a NUL-character.
.PP
The
.I n
parameter specifies the number of bytes
the binary hashsum is comprised.
.I output
needs an allocation size of (2 *
.I n
+ 1).
.SH RETURN VALUES
The
.BR libkeccak_behex_lower ()
function does return any value.
.SH ERRORS
The
.BR libkeccak_behex_lower ()
function cannot fail.
.SH SEE ALSO
.BR libkeccak_behex_upper (3),
.BR libkeccak_unhex (3)
