.TH LIBKECCAK_STATE_WIPE_MESSAGE 3 LIBKECCAK
.SH NAME
libkeccak_state_wipe_message - Securely erase the message chunk buffer
.SH SYNOPSIS
.nf
#include <libkeccak.h>

void libkeccak_state_wipe_message(struct libkeccak_state *\fIstate\fP);
.fi
.PP
Link with
.IR -lkeccak .
.SH DESCRIPTION
The
.BR libkeccak_state_wipe_message ()
function securely erases the message chunk buffer.
.SH RETURN VALUES
The
.BR libkeccak_state_wipe_message ()
function does not return any value.
.SH ERRORS
The
.BR libkeccak_state_wipe_message ()
function cannot fail.
.SH SEE ALSO
.BR libkeccak_state_wipe_sponge (3),
.BR libkeccak_state_wipe (3),
.BR libkeccak_state_fast_destroy (3),
.BR libkeccak_state_destroy (3),
.BR libkeccak_state_reset (3)
