.TH LIBKECCAK_HMAC_DESTROY 3 LIBKECCAK
.SH NAME
libkeccak_hmac_destroy - Destroys an HMAC-hashing state with erasure
.SH SYNOPSIS
.nf
#include <libkeccak.h>

void libkeccak_hmac_destroy(struct libkeccak_hmac_state *\fIstate\fP);
.fi
.PP
Link with
.IR -lkeccak .
.SH DESCRIPTION
The
.BR libkeccak_hmac_destroy ()
function releases the allocations stored in
.IR *state ,
without releasing the allocation of
.I state
itself.
.PP
The
.BR libkeccak_hmac_destroy ()
function securely erases sensitive data.
.SH RETURN VALUES
The
.BR libkeccak_hmac_destroy ()
function does not return any value.
.SH ERRORS
The
.BR libkeccak_hmac_destroy ()
function cannot fail.
.SH SEE ALSO
.BR libkeccak_hmac_free (3),
.BR libkeccak_hmac_fast_destroy (3),
.BR libkeccak_hmac_initialise (3),
.BR libkeccak_hmac_reset (3),
.BR libkeccak_hmac_wipe (3)
