.TH LIBKECCAK_HMAC_FREE 3 LIBKECCAK
.SH NAME
libkeccak_hmac_free - Destroys and deallocates an HMAC-hashing state with erasure
.SH SYNOPSIS
.nf
#include <libkeccak.h>

void libkeccak_hmac_free(struct libkeccak_hmac_state *\fIstate\fP);
.fi
.PP
Link with
.IR -lkeccak .
.SH DESCRIPTION
The
.BR libkeccak_hmac_free ()
function releases the allocations stored in
.IR *state ,
and also release the allocation of
.IR state .
.PP
The
.BR libkeccak_hmac_free ()
function securely erases sensitive data.
.SH RETURN VALUES
The
.BR libkeccak_hmac_free ()
function does not return any value.
.SH ERRORS
The
.BR libkeccak_hmac_free ()
function cannot fail.
.SH NOTES
A double call to
.BR libkeccak_hmac_free ()
will either result in a double free,
which is must likely to crash the process,
or free an allocation (that was created
between the calls) that was not intended
to be freed, resulting in undefined behaviour.
.SH SEE ALSO
.BR libkeccak_hmac_destroy (3),
.BR libkeccak_hmac_fast_free (3),
.BR libkeccak_hmac_create (3),
.BR libkeccak_hmac_initialise (3),
.BR libkeccak_hmac_reset (3),
.BR libkeccak_hmac_wipe (3)
