.TH LIBKECCAK_SPEC_SHAKE 3 LIBKECCAK
.SH NAME
libkeccak_spec_shake - Configure SHAKE hashing parameters
.SH SYNOPSIS
.nf
#include <libkeccak.h>

void libkeccak_spec_shake(struct libkeccak_spec *\fIspec\fP, long int \fIx\fP, long int \fId\fP);
.fi
.PP
Link with
.IR -lkeccak .
.SH DESCRIPTION
The
.BR libkeccak_spec_shake ()
function sets
.I *spec
to specify the Keccak parameters used for SHAKE hashing
with the semicapacity specified, in bits, via the
.I x
parameter, and the output size specified, in bits, via the
.I d
parameter.
.SH RETURN VALUES
The
.BR libkeccak_spec_shake ()
function does not return any value.
.SH ERRORS
The
.BR libkeccak_spec_shake ()
function cannot fail.
.SH EXAMPLE
This example configure a
.B struct libkeccak_spec
to specify the Keccak parameters used for SHAKE256(, 512):
.PP
.nf
struct libkeccak_spec spec;
libkeccak_spec_shake(&spec, 256, 512);
.fi
.SH SEE ALSO
.BR libkeccak_spec_cshake (3),
.BR libkeccak_spec_sha3 (3),
.BR libkeccak_spec_rawshake (3),
.BR libkeccak_spec_check (3),
.BR libkeccak_generalised_spec_initialise (3),
.BR libkeccak_state_initialise (3),
.BR libkeccak_hmac_initialise (3)
