.TH LIBKECCAK_STATE_MARSHAL 3 LIBKECCAK
.SH NAME
libkeccak_state_marshal - Marshals a hash state
.SH SYNOPSIS
.LP
.nf
#include <libkeccak.h>
.P
size_t
libkeccak_state_marshal(const libkeccak_state_t *\fIstate\fP, char *\fIdata\fP);
.fi
.P
Link with
.IR -lkeccak .
.SH DESCRIPTION
The
.BR libkeccak_state_marshal ()
function marshals \fI*state\fP into the beginning of
.IR data .
.PP
Use the
.BR libkeccak_state_marshal_size (3)
function to get minimum usable allocation size
for
.IR data .
.SH RETURN VALUES
The
.BR libkeccak_state_marshal ()
returns the number of bytes written to
.IR data .
.SH ERRORS
The
.BR libkeccak_state_marshal ()
function cannot fail.
.SH SEE ALSO
.BR libkeccak_state_marshal_size (3),
.BR libkeccak_state_unmarshal (3),
.BR libkeccak_state_unmarshal_skip (3)
.SH BUGS
Please report bugs to https://github.com/maandree/libkeccak/issues or to
maandree@kth.se
