.TH LIBKECCAK_HMAC_UNMARSHAL_SKIP 3 LIBKECCAK-%VERSION%
.SH NAME
libkeccak_hmac_unmarshal_skip - Calculates the marshal-size of a marshalled HMAC-hashing state
.SH SYNOPSIS
.LP
.nf
#include <libkeccak.h>
.P
size_t libkeccak_hmac_unmarshal_skip(const char *\fIdata\fP);
.fi
.P
Link with \fI-lkeccak\fP.
.SH DESCRIPTION
The
.BR libkeccak_hmac_unmarshal_skip ()
function gets the number of bytes with which
the HMAC-hashing state in the beginning of \fIdata\fP
is store stored. This is useful if you do not
want to unmarshal the state.
.SH RETURN VALUES
The
.BR libkeccak_hmac_unmarshal_skip ()
returns a positive value: the number of
bytes to skip forward to skip pass the
hash state stored at the beginning of
the buffer.
.SH ERRORS
The
.BR libkeccak_hmac_unmarshal_skip ()
function cannot fail.
.SH SEE ALSO
.BR libkeccak_hmac_marshal_size (3),
.BR libkeccak_hmac_marshal (3),
.BR libkeccak_hmac_unmarshal (3)
.SH AUTHORS
Principal author, Mattias Andrée.  See the LICENSE file for the full
list of authors.
.SH BUGS
Please report bugs to https://github.com/maandree/libkeccak/issues or to
maandree@member.fsf.org
