.TH LIBKECCAK_HMAC_CREATE 3 LIBKECCAK-%VERSION%
.SH NAME
libkeccak_hmac_create - Allocate and initialise HMAC-hashing state
.SH SYNOPSIS
.LP
.nf
#include <libkeccak.h>
.P
libkeccak_hmac_state_t *libkeccak_hmac_create(const libkeccak_spec_t *\fIspec\fP,
                                              const char *\fIkey\fP, size_t \fIkey_length\fP);
.fi
.P
Link with \fI-lkeccak\fP.
.SH DESCRIPTION
The
.BR libkeccak_hmac_create ()
function allocates a new \fIlibkeccak_hmac_state_t*\fP with one
initialised element, and sets the algorithm tuning parameters to
those specified by \fI*spec\fP, and the key to \fIkey\fP of
length \fIkey_length\fP.
.SH RETURN VALUES
The
.BR libkeccak_hmac_create ()
function returns a newly allocated \fIlibkeccak_hmac_state_t*\fP
(of one initialised element) upon successful completion.
On error, \fINULL\fP is returned and \fIerrno\fP is set to
describe the error.
.SH ERRORS
The
.BR libkeccak_hmac_create ()
function may fail for any specified for the functions
.BR malloc (3)
and
.BR realloc (3).
.SH SEE ALSO
.BR libkeccak_hmac_initialise (3),
.BR libkeccak_hmac_free (3),
.BR libkeccak_hmac_fast_free (3),
.BR libkeccak_hmac_duplicate (3)
.SH AUTHORS
Principal author, Mattias Andrée.  See the LICENSE file for the full
list of authors.
.SH BUGS
Please report bugs to https://github.com/maandree/libkeccak/issues or to
maandree@kth.se
