.TH LIBKECCAK_STATE_DUPLICATE 3 LIBKECCAK
.SH NAME
libkeccak_state_duplicate - Allocate a duplicate hash state
.SH SYNOPSIS
.LP
.nf
#include <libkeccak.h>
.P
libkeccak_state_t *
libkeccak_state_duplicate(const libkeccak_state_t *\fIsrc\fP);
.fi
.P
Link with
.IR -lkeccak P.
.SH DESCRIPTION
The
.BR libkeccak_state_duplicate ()
function allocates a new hash state and initialises it
to be identical to
.IR *src .
This includes all members of the
.B libkeccak_state_t
structure, including the state of the sponge and the
message chunk buffer.
.SH RETURN VALUES
The
.BR libkeccak_state_duplicate ()
function returns a newly allocated
.I libkeccak_state_t*
(of one initialised element) upon successful completion.
On error,
.I NULL
is returned and
.I errno
is set to describe the error.
.SH ERRORS
The
.BR libkeccak_state_duplicate ()
function may fail for any specified for the function
.BR malloc (3).
.SH SEE ALSO
.BR libkeccak_state_copy (3),
.BR libkeccak_state_create (3)
.SH BUGS
Please report bugs to https://github.com/maandree/libkeccak/issues or to
maandree@kth.se
