.TH LIBKECCAK_UNHEX 3 LIBKECCAK
.SH NAME
libkeccak_unhex - Converts a hexadecimal hashsum to binary
.SH SYNOPSIS
.nf
#include <libkeccak.h>

void libkeccak_unhex(void *restrict \fIoutput\fP, const char *restrict \fIhashsum\fP);
.fi
.PP
Link with
.IR -lkeccak .
.SH DESCRIPTION
The
.BR libkeccak_unhex ()
function
converts a hexadecimal hashsum, stored in
.IR hashsum ,
to binary, and stores the binary representation in
.IR output .
.PP
.I hashsum
must be terminated by a NUL-character. It may be
in either lowercase or uppercase, or a mixture
thereof.
.I output
will not be terminated.
.PP
(\fBstrlen\fP(\fIhashsum\fP) / 2) bytes will be
written to the beginning of
.IR Ioutput .
It should therefore have an allocation of at least
that number of bytes.
.SH RETURN VALUES
The
.BR libkeccak_unhex ()
function does return any value.
.SH ERRORS
The
.BR libkeccak_unhex ()
function cannot fail.
.SH NOTES
.I hashsum
must have an even number of digits
(characters excluding the terminating NUL-character.)
.SH SEE ALSO
.BR libkeccak_behex_lower (3),
.BR libkeccak_behex_upper (3)
