.TH LIBKECCAK_FAST_SQUEEZE 3 LIBKECCAK
.SH NAME
libkeccak_squeeze - Runs the squeeze phase
.SH SYNOPSIS
.nf
#include <libkeccak.h>

void libkeccak_squeeze(struct libkeccak_state *\fIstate\fP, void *\fIhashsum\fP);
.fi
.PP
Link with
.IR -lkeccak .
.SH DESCRIPTION
The
.BR libkeccak_squeeze ()
function runs the Keccak squeeze phase, on the the hash
process described by
.IR *state ,
on stores a new digest, in binary form, in
.IR hashsum .
.PP
.I hashsum
has the same requirement as for the
.BR libkeccak_digest (3)
and
.BR libkeccak_fast_digest (3)
functions: it must have an allocation size of at least
.RI (( state->n
+ 7) / 8) bytes. However, it may not be
.IR NULL .
.SH RETURN VALUES
The
.BR libkeccak_squeeze ()
function does not return any value.
.SH ERRORS
The
.BR libkeccak_squeeze ()
function cannot fail.
.SH SEE ALSO
.BR libkeccak_digest (3),
.BR libkeccak_fast_digest (3),
.BR libkeccak_zerocopy_digest (3),
.BR libkeccak_simple_squeeze (3),
.BR libkeccak_fast_squeeze (3)
