.TH LIBKECCAK_GENERALISED_SPEC_INITIALISE 3 LIBKECCAK
.SH NAME
libkeccak_generalised_spec_initialise - Set all specification parameters to automatic
.SH SYNOPSIS
.nf
#include <libkeccak.h>

void libkeccak_generalised_spec_initialise(struct libkeccak_generalised_spec *\fIspec\fP);
.fi
.PP
Link with
.IR -lkeccak .
.SH DESCRIPTION
The
.BR libkeccak_generalised_spec_initialise ()
function initialises
.IR *spec ,
so that all parameters are configured to be
automatically selected.
.PP
Automatic selection means that value will be set
to the default, which depends on the other settings.
.PP
Specifically, all members of
.IR *spec ,
will be set to
.BR LIBKECCAK_GENERALISED_SPEC_AUTOMATIC .
.SH RETURN VALUES
The
.BR libkeccak_generalised_spec_initialise ()
function does not return any value.
.SH ERRORS
The
.BR libkeccak_generalised_spec_initialise ()
function cannot fail.
.fi
.SH SEE ALSO
.BR libkeccak_degeneralise_spec (3),
.BR libkeccak_spec_cshake (3),
.BR libkeccak_spec_sha3 (3),
.BR libkeccak_spec_rawshake (3),
.BR libkeccak_spec_shake (3)
