.TH LIBKECCAK_STATE_CREATE 3 LIBKECCAK
.SH NAME
libkeccak_state_create - Allocate and initialise hash state
.SH SYNOPSIS
.nf
#include <libkeccak.h>

struct libkeccak_state *libkeccak_state_create(const struct libkeccak_spec *\fIspec\fP);
.fi
.PP
Link with
.IR -lkeccak .
.SH DESCRIPTION
The
.BR libkeccak_state_create ()
function allocates a new
.I struct libkeccak_state *
with one initialised element, and sets the algorithm
tuning parameters to those specified by
.IR *spec .
.SH RETURN VALUES
The
.BR libkeccak_state_create ()
function returns a newly allocated
.I struct libkeccak_state *
(of one initialised element) upon successful completion.
On error,
.I NULL
is returned and
.I errno
is set to describe the error.
.SH ERRORS
The
.BR libkeccak_state_create ()
function may fail for any specified for the function
.BR malloc (3).
.SH SEE ALSO
.BR libkeccak_state_initialise (3),
.BR libkeccak_state_free (3),
.BR libkeccak_state_fast_free (3)
.BR libkeccak_state_duplicate (3)
