.TH LIBKECCAK_HMAC_SET_KEY 3 LIBKECCAK
.SH NAME
libkeccak_hmac_set_key - Changes key for a the HMAC-hashing state
.SH SYNOPSIS
.nf
#include <libkeccak.h>

int libkeccak_hmac_set_key(struct libkeccak_hmac_state *\fIstate\fP, const void *\fIkey\fP, size_t \fIkey_length\fP);
.fi
.PP
Link with
.IR -lkeccak .
.SH DESCRIPTION
The
.BR libkeccak_hmac_set_key ()
function sets the key for a HMAC-hashing state without reseting
the state of the underlaying hashing-algorithm.
.I key_length
is the length of the key in bits.
.SH RETURN VALUES
The
.BR libkeccak_hmac_set_key ()
function returns 0 successful completion.
On error -1 is returned and
.I errno
is set to describe the error.
.SH ERRORS
The
.BR libkeccak_hmac_set_key ()
function may fail for any specified for the function
.BR realloc (3).
.SH SEE ALSO
.BR libkeccak_hmac_create (3),
.BR libkeccak_hmac_initialise (3),
.BR libkeccak_hmac_reset (3)
