.TH LIBKECCAK_HMAC_MARSHAL_SIZE 3 LIBKECCAK
.SH NAME
libkeccak_hmac_marshal_size - Calculates the marshal-size of an HMAC-hashing state
.SH SYNOPSIS
.LP
.nf
#include <libkeccak.h>
.P
size_t
libkeccak_hmac_marshal_size(const libkeccak_hmac_state_t *\fIstate\fP);
.fi
.P
Link with
.IR -lkeccak .
.SH DESCRIPTION
The
.BR libkeccak_hmac_marshal_size ()
function calculates the number of bytes required
to marshal
.IR *state .
.SH RETURN VALUES
The
.BR libkeccak_hmac_marshal_size ()
returns a positive value: the number of
bytes required to marshal the specified state.
.SH ERRORS
The
.BR libkeccak_hmac_marshal_size ()
function cannot fail.
.SH SEE ALSO
.BR libkeccak_hmac_marshal (3),
.BR libkeccak_hmac_unmarshal (3),
.BR libkeccak_hmac_unmarshal_skip (3)
.SH BUGS
Please report bugs to https://github.com/maandree/libkeccak/issues or to
maandree@kth.se
