.TH LIBKECCAK_HMAC_UPDATE 3 LIBKECCAK
.SH NAME
libkeccak_hmac_update - Partially HMAC-hash a message with erasure
.SH SYNOPSIS
.nf
#include <libkeccak.h>

int libkeccak_hmac_update(struct libkeccak_state *\fIstate\fP, const void *\fImsg\fP, size_t \fImsglen\fP);
.fi
.PP
Link with
.IR -lkeccak .
.SH DESCRIPTION
The
.BR libkeccak_hmac_update ()
function continues (or starts) HMAC-hashing a message.
The current state of the hashing is stored in
.IR *state ,
and will be updated. The message specified by the
.I msg
parameter with the byte-size specified by the
.I msglen
parameter, will be hashed.
.PP
The
.BR libkeccak_hmac_update ()
function may reallocate the state's message chunk buffer.
When doing so, it attempts to do so as securely as possible,
rather than as fast as possible.
.SH RETURN VALUES
The
.BR libkeccak_hmac_update ()
function returns 0 upon successful completion. On error,
-1 is returned and
.I errno
is set to describe the error.
.SH ERRORS
The
.BR libkeccak_hmac_update ()
function may fail for any reason specified by the function
.BR malloc (3).
.SH NOTES
Neither parameter by be
.I NULL
or 0.
.SH SEE ALSO
.BR libkeccak_hmac_create (3),
.BR libkeccak_hmac_initialise (3),
.BR libkeccak_hmac_digest (3),
.BR libkeccak_hmac_fast_update (3)
