.TH LIBKECCAK_SPEC_SHA3 3 LIBKECCAK
.SH NAME
libkeccak_spec_sha3 - Configure SHA-3 hashing parameters
.SH SYNOPSIS
.nf
#include <libkeccak.h>

void libkeccak_spec_sha3(struct libkeccak_spec *\fIspec\fP, long int \fIx\fP);
.fi
.PP
Link with
.IR -lkeccak .
.SH DESCRIPTION
The
.BR libkeccak_spec_sha3 ()
function sets
.I *spec
to specify the Keccak parameters
used for SHA-3 hashing with the output size specified,
in bits, via the
.I x
parameter.
.SH RETURN VALUES
The
.BR libkeccak_spec_sha3 ()
function does not return any value.
.SH ERRORS
The
.BR libkeccak_spec_sha3 ()
function cannot fail.
.SH EXAMPLE
This example configure a
.B struct libkeccak_spec
to specify the Keccak parameters used for SHA3-256:
.PP
.nf
struct libkeccak_spec spec;
libkeccak_spec_sha3(&spec, 256);
.fi
.SH SEE ALSO
.BR libkeccak_spec_cshake (3),
.BR libkeccak_spec_rawshake (3),
.BR libkeccak_spec_shake (3),
.BR libkeccak_spec_check (3),
.BR libkeccak_generalised_spec_initialise (3),
.BR libkeccak_state_initialise (3),
.BR libkeccak_hmac_initialise (3)
