.TH LIBKECCAK_STATE_DUPLICATE 3 LIBKECCAK
.SH NAME
libkeccak_state_duplicate - Allocate a duplicate hash state
.SH SYNOPSIS
.nf
#include <libkeccak.h>

struct libkeccak_state *libkeccak_state_duplicate(const struct libkeccak_state *\fIsrc\fP);
.fi
.PP
Link with
.IR -lkeccak P.
.SH DESCRIPTION
The
.BR libkeccak_state_duplicate ()
function allocates a new hash state and initialises it
to be identical to
.IR *src .
This includes all members of the
.B struct libkeccak_state
structure, including the state of the sponge and the
message chunk buffer.
.SH RETURN VALUES
The
.BR libkeccak_state_duplicate ()
function returns a newly allocated
.I struct libkeccak_state*
(of one initialised element) upon successful completion.
On error,
.I NULL
is returned and
.I errno
is set to describe the error.
.SH ERRORS
The
.BR libkeccak_state_duplicate ()
function may fail for any specified for the function
.BR malloc (3).
.SH SEE ALSO
.BR libkeccak_state_copy (3),
.BR libkeccak_state_create (3)
