.TH LIBKECCAK_STATE_INITIALISE 3 LIBKECCAK
.SH NAME
libkeccak_state_initialise - Initialise hash state
.SH SYNOPSIS
.nf
#include <libkeccak.h>

int libkeccak_state_initialise(struct libkeccak_state *\fIstate\fP, const struct libkeccak_spec *\fIspec\fP);
.fi
.PP
Link with
.IR -lkeccak .
.SH DESCRIPTION
The
.BR libkeccak_state_initialise ()
function initialises
.I *state
and sets the algorithm tuning parameters to those
specified by
.IR *spec .
.SH RETURN VALUES
The
.BR libkeccak_state_initialise ()
function returns 0 upon successful completion.
On error, -1 is returned and
.I errno
is set to describe the error.
.SH ERRORS
The
.BR libkeccak_state_initialise ()
function may fail for any specified for the function
.BR malloc (3).
.SH SEE ALSO
.BR libkeccak_state_create (3),
.BR libkeccak_state_reset (3),
.BR libkeccak_state_destroy (3),
.BR libkeccak_state_fast_destroy (3),
.BR libkeccak_state_copy (3),
.BR libkeccak_fast_update (3),
.BR libkeccak_zerocopy_update (3),
.BR libkeccak_update (3),
.BR libkeccak_fast_digest (3),
.BR libkeccak_zerocopy_digest (3),
.BR libkeccak_digest (3),
.BR libkeccak_generalised_sum_fd (3),
.BR libkeccak_keccaksum_fd (3),
.BR libkeccak_sha3sum_fd (3),
.BR libkeccak_rawshakesum_fd (3),
.BR libkeccak_shakesum_fd (3),
.BR libkeccak_spec_cshake (3),
.BR libkeccak_spec_sha3 (3),
.BR libkeccak_spec_shake (3),
.BR libkeccak_spec_rawshake (3),
.BR libkeccak_spec_check (3),
.BR libkeccak_generalised_spec_initialise (3),
.BR libkeccak_state_marshal (3),
.BR libkeccak_hmac_initialise (3)
